imports:
    - { resource: '@PrestaCMSThemeBasicBundle/Resources/config/theme/creative.yml' }

parameters:
    presta_cms.page.factory.class: Application\Presta\CMSCoreBundle\Factory\PageFactory

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_cms_core:
    default_website: /website/sandbox
    default_locale: en
    websites:
        prestacms-sandbox:
            path: /website/sandbox
            hosts:
                dev:
                    en:
                        locale: en
                        host: dev-prestacms-sandbox.com
                    fr:
                        locale: fr
                        host: dev-prestacms-sandbox.fr
                prod:
                    en:
                        locale: en
                        host: sandbox.prestacms.com
                    fr:
                        locale: fr
                        host:  sandbox.prestacms.fr
                integration:
                    en:
                        locale: en
                        host:  en.prestacms-sandbox.integration54.local
                    fr:
                        locale: fr
                        host:  fr.prestacms-sandbox.integration54.local
    blocks:
        global:
            excluded:
                - presta_cms.block.ajax
        left:
            excluded:
                - presta_cms.block.media_advanced
        presta_cms.block.container:
            excluded:
                - presta_cms.block.page_children
